import { PropsWithChildren, ReactNode } from "react";
import Head from "next/head";

const HeadMetadata: React.FC<PropsWithChildren> = () => {
  return (
    <Head>
        <title>Retro Stuff Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
  );
};

export default HeadMetadata;
