import Head from "next/head";
import React from "react";
import Title from "../components/Title";
import * as prd from "../lib/products"

export async function getServerSideProps() {
  const products = await prd.getProductsFromApi();

  return {
    props: {
      products
    }
  };
}

const HomePage: React.FC = ({products}: any) => {
  console.log(products);
  return (
    <>
      <Head>
        <title>NextJS Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="p-6">
        <Title>Retro Consoles Shop</Title>
        <ul className="dark:text-gray-300">
          {products.map((product) => (
            <li key={product.id}>{product.title}</li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default HomePage;
