import Head from "next/head";
import React from "react";
import Title from "../components/Title";

const HomePage: React.FC = () => {
  return (
    <>
      <Head>
        <title>NextJS Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="p-6">
        <Title>NextJS Shop</Title>
        <p className="dark:text-gray-300">Shop content</p>
      </main>
    </>
  );
};

export default HomePage;
