import Head from 'next/head'
import React from 'react';

const HomePage: React.FC = () => {
  return (
    <>
      <Head>
        <title>NextJS Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>
          NextJS Shop
        </h1>
      </main>
    </>
  )
}

export default HomePage;
